image: etna/drone-php7:php71
env:
  - APPLICATION_ENV=test
  - COVERALLS_REPO_TOKEN=$$COVERALLS_TOKEN
  - COVERALLS_SERVICE_NAME=drone.io
script:
  - nb=1 ; while [ $nb -lt 20 ] && ! echo "show elasticsearch;" | curl -XGET "http://127.0.0.1:9200" ; do echo "Try n $nb ES is not ready"; nb=$(($nb + 1)); sleep 1; done
  - composer global require phpdocumentor/phpdocumentor --no-interaction --prefer-dist --no-progress
  - composer install --dev --no-interaction --prefer-dist --no-progress
  - composer phing
  - composer coveralls
services:
  - bluetna/drone-elasticsearch
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: $$SLACK_CHANNEL
    on_started: true
    on_failure: true
    on_success: true
