---
README.md:
    name: "elasticsearch-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6e68e78abc191000030/badge.svg)](https://www.versioneye.com/user/projects/53dde6e68e78abc191000030)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-elasticsearch-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-elasticsearch-service-provider/?branch=master)"
